### Signup - Create a new user
POST http://localhost:3001/signup-buyer
Content-Type: application/json

{
  "email": "testbuyer@example.com",
  "password": "testpassword",
  "company_name": "Example Corp",
  "cnpj": "12.345.678/0001-90",
  "address": "123 Main St",
  "phone1": "123-456-7890",
  "phone2": "098-765-4321",
  "responsible_name": "John Doe",
  "responsible_cpf": "123.456.789-00",
  "responsible_phone": "123-456-7890",
  "responsible_position": "Manager"
}

### Test Signup with an existing email (should fail)
POST http://localhost:3001/signup
Content-Type: application/json

{
  "email": "testbuyer@example.com",
  "password": "anotherpassword",
  "company_name": "Another Corp",
  "cnpj": "12.345.678/0002-90",
  "address": "456 Another St",
  "phone1": "987-654-3210",
  "phone2": "876-543-2109",
  "responsible_name": "Jane Doe",
  "responsible_cpf": "321.654.987-00",
  "responsible_phone": "987-654-3210",
  "responsible_position": "CEO"
}

### Login - Authenticate user
POST http://localhost:3001/login
Content-Type: application/json

{
  "email": "testbuyer@example.com",
  "password": "testpassword"
}

### Test Login with incorrect password (should fail)
POST http://localhost:3001/login
Content-Type: application/json

{
  "email": "testbuyer@example.com",
  "password": "wrongpassword"
}

### Access Protected Route - with valid token
GET http://localhost:3001/protected-route
Cookie: jwt={{token_from_login_response}}

### Access Protected Route - without token (should fail)
GET http://localhost:3000/protected-route

### Logout - Clear JWT Cookie
POST http://localhost:3000/logout

